In [1]:
import pandas as pd
df=pd.read_csv('Movies Dataset.csv')
df

,id,title,genres,original_language,overview,popularity,production_companies,release_date,budget,revenue,runtime,status,tagline,vote_average,vote_count,credits,keywords,poster_path,backdrop_path,recommendations
0,385687,Fast X,Action-Crime-Thriller,en,Over many missions and against impossible odds...,6682.100,Universal Pictures-Original Film-One Race-Perf...,2023-05-17,340000000.0,6.867000e+08,142.0,Released,The end of the road begins.,7.331,1856.0,Vin Diesel-Michelle Rodriguez-Tyrese Gibson-Lu...,sequel-revenge-racing-family-cars,/fiVW06jE7z9YnO4trhaMEdclSiC.jpg,/4XM8DUTQb3lhLemJC51Jx4a2EuA.jpg,19603-445954-697843-603692-781009-502356-74735...
1,758323,The Pope's Exorcist,Horror-Mystery-Thriller,en,Father Gabriele Amorth Chief Exorcist of the V...,5953.227,Screen Gems-2.0 Entertainment-Jesus & Mary-Wor...,2023-04-05,18000000.0,6.567582e+07,103.0,Released,Inspired by the actual files of Father Gabriel...,7.433,545.0,Russell Crowe-Daniel Zovatto-Alex Essoe-Franco...,spain-rome italy-vatican-pope-pig-possession-c...,/9JBEPLTPSm0d1mbEcLxULjJq9Eh.jpg,/hiHGRbyTcbZoLsYYkO4QiCLYe34.jpg,713704-296271-502356-1076605-1084225-1008005-9...
2,640146,Ant-Man and the Wasp: Quantumania,Action-Adventure-Science Fiction,en,Super-Hero partners Scott Lang and Hope van Dy...,4425.387,Marvel Studios-Kevin Feige Productions,2023-02-15,200000000.0,4.757662e+08,125.0,Released,Witness the beginning of a new dynasty.,6.507,2811.0,Paul Rudd-Evangeline Lilly-Jonathan Majors-Kat...,hero-ant-sequel-superhero-based on comic-famil...,/qnqGbB22YJ7dSs4o6M7exTpNxPz.jpg,/m8JTwHFwX7I7JY5fPe4SjqejWag.jpg,823999-676841-868759-734048-267805-965839-1033...
3,677179,Creed III,Drama-Action,en,After dominating the boxing world Adonis Creed...,3994.342,Metro-Goldwyn-Mayer-Proximity Media-Balboa Pro...,2023-03-01,75000000.0,2.690000e+08,116.0,Released,You can't run from your past.,7.262,1129.0,Michael B. Jordan-Tessa Thompson-Jonathan Majo...,philadelphia pennsylvania-husband wife relatio...,/cvsXj3I9Q2iyyIo95AecSd1tad7.jpg,/5i6SjyDbDWqyun8klUuCxrlFbyw.jpg,965839-267805-943822-842942-1035806-823999-107...
4,502356,The Super Mario Bros. Movie,Animation-Family-Adventure-Fantasy-Comedy,en,While working underground to fix a water main ...,3859.926,Universal Pictures-Illumination-Nintendo,2023-04-05,100000000.0,1.278767e+09,92.0,Released,NaN,7.764,4042.0,Chris Pratt-Charlie Day-Anya Taylor-Joy-Jack B...,video game-gorilla-plumber-magic mushroom-anth...,/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg,/2klQ1z1fcHGgQPevbEQdkCnzyuS.jpg,713704-385687-640146-60898-758323-1008005-4935...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
722791,900760,A Incessante Conquista da Escuridão,NaN,pt,Two voices talk about the impermanence of the ...,0.600,NaN,2021-04-15,0.0,0.000000e+00,10.0,Released,NaN,0.000,0.0,Rita Poças,NaN,/l2cEYTvqgsi0tvxRHZYdEQKPBLM.jpg,NaN,NaN
722792,957818,Hollywood Varieties,Comedy,en,Entertainment trade-paper headlines report the...,0.600,NaN,1950-01-01,0.0,0.000000e+00,60.0,Released,Big time Vaudeville on the screen,0.000,0.0,Robert Alda-Ken Trietsch-Paul Trietsch-Al Shaw...,NaN,NaN,NaN,NaN
722793,648905,A Man Must Be Strong,NaN,it,Jack starts the transition in order to let his...,0.600,NaN,2019-11-19,0.0,0.000000e+00,61.0,Released,NaN,0.000,0.0,NaN,NaN,/fKvCVxVjShCTTOpBZeOYGsEwisK.jpg,NaN,NaN
722794,576855,Stastriptease,NaN,de,NaN,0.600,NaN,2018-06-07,0.0,0.000000e+00,NaN,Released,NaN,0.000,0.0,NaN,NaN,NaN,NaN,NaN
722795,968161,Gising Sining,NaN,tl,In a country where fascism foolishness of peop...,0.600,Studio RD,NaN,0.0,0.000000e+00,19.0,Released,NaN,0.000,0.0,Ruka Azuma-Mel Perez,NaN,/jv34KgS7D997H5kbVYxKLJRScg.jpg,NaN,NaN

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 722796 entries, 0 to 722795
Data columns (total 20 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   id                    722796 non-null  int64
 1   title                 722790 non-null  object
 2   genres                511934 non-null  object
 3   original_language     722796 non-null  object
 4   overview              604198 non-null  object
 5   popularity            722796 non-null  float64
 6   production_companies  337170 non-null  object
 7   release_date          670329 non-null  object
 8   budget                722796 non-null  float64
 9   revenue               722796 non-null  float64
 10  runtime               688346 non-null  float64
 11  status                722796 non-null  object
 12  tagline               108098 non-null  object
 13  vote_average          722796 non-null  float64
 14  vote_count            722796 non-null  float64
 15  credits               497689 non-null  object
 16  keywords              210271 non-null  object
 17  poster_path           537566 non-null  object
 18  backdrop_path         222524 non-null  object
 19  recommendations       34720 non-null   object
dtypes: float64(6), int64(1), object(13)
memory usage: 110.3+ MB

In [5]:
df.isnull().sum()

id                           0
title                        6
genres                  210862
original_language            0
overview                118598
popularity                   0
production_companies    385626
release_date             52467
budget                       0
revenue                      0
runtime                  34450
status                       0
tagline                 614698
vote_average                 0
vote_count                   0
credits                 225107
keywords                512525
poster_path             185230
backdrop_path           500272
recommendations         688076
dtype: int64

In [15]:
column_to_drop=['credits', 'poster_path','backdrop_path','keywords','tagline','overview','runtime','recommendations']

In [17]:
df_cleaned=df.drop(columns=column_to_drop)
df_cleaned

,id,title,genres,original_language,popularity,production_companies,release_date,budget,revenue,status,vote_average,vote_count
0,385687,Fast X,Action-Crime-Thriller,en,6682.100,Universal Pictures-Original Film-One Race-Perf...,2023-05-17,340000000.0,6.867000e+08,Released,7.331,1856.0
1,758323,The Pope's Exorcist,Horror-Mystery-Thriller,en,5953.227,Screen Gems-2.0 Entertainment-Jesus & Mary-Wor...,2023-04-05,18000000.0,6.567582e+07,Released,7.433,545.0
2,640146,Ant-Man and the Wasp: Quantumania,Action-Adventure-Science Fiction,en,4425.387,Marvel Studios-Kevin Feige Productions,2023-02-15,200000000.0,4.757662e+08,Released,6.507,2811.0
3,677179,Creed III,Drama-Action,en,3994.342,Metro-Goldwyn-Mayer-Proximity Media-Balboa Pro...,2023-03-01,75000000.0,2.690000e+08,Released,7.262,1129.0
4,502356,The Super Mario Bros. Movie,Animation-Family-Adventure-Fantasy-Comedy,en,3859.926,Universal Pictures-Illumination-Nintendo,2023-04-05,100000000.0,1.278767e+09,Released,7.764,4042.0
...,...,...,...,...,...,...,...,...,...,...,...,...
722791,900760,A Incessante Conquista da Escuridão,NaN,pt,0.600,NaN,2021-04-15,0.0,0.000000e+00,Released,0.000,0.0
722792,957818,Hollywood Varieties,Comedy,en,0.600,NaN,1950-01-01,0.0,0.000000e+00,Released,0.000,0.0
722793,648905,A Man Must Be Strong,NaN,it,0.600,NaN,2019-11-19,0.0,0.000000e+00,Released,0.000,0.0
722794,576855,Stastriptease,NaN,de,0.600,NaN,2018-06-07,0.0,0.000000e+00,Released,0.000,0.0
722795,968161,Gising Sining,NaN,tl,0.600,Studio RD,NaN,0.0,0.000000e+00,Released,0.000,0.0

In [19]:
df_cleaned.isnull().sum()

id                           0
title                        6
genres                  210862
original_language            0
popularity                   0
production_companies    385626
release_date             52467
budget                       0
revenue                      0
status                       0
vote_average                 0
vote_count                   0
dtype: int64

In [23]:
numerical=df_cleaned.select_dtypes(include=['number']).columns
numerical

Index(['id', 'popularity', 'budget', 'revenue', 'vote_average', 'vote_count'], dtype='object')

In [25]:
categorical=df_cleaned.select_dtypes(include=['object']).columns
categorical

Index(['title', 'genres', 'original_language', 'production_companies',
       'release_date', 'status'],
      dtype='object')

In [27]:
df_cleaned[numerical]=df_cleaned[numerical].fillna(df_cleaned[numerical].mode)

In [29]:
df_cleaned[categorical]=df_cleaned[categorical].fillna('unknown')

In [31]:
df_cleaned.isnull().sum()

id                      0
title                   0
genres                  0
original_language       0
popularity              0
production_companies    0
release_date            0
budget                  0
revenue                 0
status                  0
vote_average            0
vote_count              0
dtype: int64

In [38]:
from sklearn.preprocessing import LabelEncoder
label={}
for col in categorical:
    le=LabelEncoder()
    df_cleaned[col]=le.fit_transform(df_cleaned[col])
    label[col]=le
df_cleaned.head()

,id,title,genres,original_language,popularity,production_companies,release_date,budget,revenue,status,vote_average,vote_count
0,385687,158347,691,32,6682.100,134069,41036,340000000.0,6.867000e+08,4,7.331,1856.0
1,758323,479568,7785,32,5953.227,112986,41001,18000000.0,6.567582e+07,4,7.433,545.0
2,640146,39911,300,32,4425.387,81244,40959,200000000.0,4.757662e+08,4,6.507,2811.0
3,677179,103814,4973,32,3994.342,83305,40972,75000000.0,2.690000e+08,4,7.262,1129.0
4,502356,490232,2747,32,3859.926,133935,41001,100000000.0,1.278767e+09,4,7.764,4042.0

In [40]:
from sklearn.preprocessing import StandardScaler
scaler={}
for col in numerical:
    sc=StandardScaler()
    df_cleaned[col]=sc.fit_transform(df_cleaned[[col]])
    scaler[col]=sc
df_cleaned.head()

,id,title,genres,original_language,popularity,production_companies,release_date,budget,revenue,status,vote_average,vote_count
0,-0.557861,158347,691,32,354.591895,134069,41036,41.740437,34.100161,4,1.539250,4.792339
1,0.914052,479568,7785,32,315.903103,112986,41001,2.164103,3.217364,4,1.571371,1.356114
2,0.447253,39911,300,32,234.804910,81244,40959,24.533335,23.610674,4,1.279763,7.295461
3,0.593533,103814,4973,32,211.924915,83305,40972,9.169851,13.328435,4,1.517521,2.886820
4,-0.097018,490232,2747,32,204.790074,133935,41001,12.242548,63.542951,4,1.675607,10.522000

In [48]:
df_cleaned.to_csv('D:/Backups/E/kaggledataset/cleaned_movies.csv',index=False)
df_cleaned.head()

,id,title,genres,original_language,popularity,production_companies,release_date,budget,revenue,status,vote_average,vote_count
0,-0.557861,158347,691,32,354.591895,134069,41036,41.740437,34.100161,4,1.539250,4.792339
1,0.914052,479568,7785,32,315.903103,112986,41001,2.164103,3.217364,4,1.571371,1.356114
2,0.447253,39911,300,32,234.804910,81244,40959,24.533335,23.610674,4,1.279763,7.295461
3,0.593533,103814,4973,32,211.924915,83305,40972,9.169851,13.328435,4,1.517521,2.886820
4,-0.097018,490232,2747,32,204.790074,133935,41001,12.242548,63.542951,4,1.675607,10.522000